### ISSUE TITLE
Couple minor fixes on agg_

### ISSUE THREAD

**Issue by adelavega** [rbroc/reading_brain_prep#1]
I was looking at the agg_ transcripts and just found a couple issues:

- The last two items in this file: https://github.com/rbroc/reading_brain_prep/blob/master/processed_data/sub-01/func/agg_sub-01_task-read_run-1_events.tsv (and maybe other files) have an onset of `0`. Any idea why?
- There are a few numbers as words, any idea why? Can we strip these?
- There are also a few blank lines, can we also strip these?

Otherwise, looking good and I think we can try to ingest soon. 

Going forward, I think we should host a forked version of the dataset on Neuroscout and on github (w/ datalad), to keep track of the changes we've made. Probably there will be other BIDS non-complicance issues when I try to ingest.

**Comment by rbroc** [comment]
Ale, thanks for pointing out the onset issue! It should be fixed now, it's a weird indexing issue arising from pandas `append` / `concat`. I'm not sure I fully understand why that happens, but when a new Series is appended at the end it get index `0` unless `ignore_index=True`. The dataframe is then automatically reindexed when a new iteration of row concatenation is run so that the second-last row gets the "correct" index, i.e. +1 relative to previous row. For some event files, however, this did not happen for the last couple of onsets.
Anyway, it'd probably take a while to figure out why exactly this happened, but the issue should be fixed by setting `ignore_index=True` and manually resetting the index at each iteration.
Would be awesome if you took a quick look to see if you can spot other potential errors.

I've now removed columns with blank lines and numbers.

I also emailed to the authors asking for a description of the word norms file columns. They were superquick in getting back, I've updated the dictionary json according to their replies :)

**Comment by adelavega** [comment]
Okay, great, looking good.

One more very minor fix. When you save the csvs, can you use `ignore_index` as well? I want to avoid the index column (the first column) being saved out. 

No worries, I probably won't try to ingest this until next week.

**Comment by rbroc** [comment]
should be done now.
